version: '2'

services:
    ubuntu:
        image: my-ubuntu
        build: .
        networks:
            - my_net
        volumes:
            # Change this to your own directory for bind mount
            - ~/Developer/Go/playground:/root/playground
networks:
    my_net:
        driver: bridge